### ISSUE TITLE
bin/install and bin/vimbundle.sh do not exit with a status code of 0

### ISSUE THREAD

**Issue by rondale-sc** [hashrocket/dotmatrix#25]
This caused me pain.  Don't know of exact fix.  I had to workaround this with:

`sh -c './bin/install ; true'` 

Which basically says, this command was successful no matter what (BAD BAD BAD).  

Case was for a Vagrant provisioning line.  Vagrant provisioning fails if it ever encounters a non-zero return.

**Comment by jgdavey** [comment]
This *should* be solved on master now, although I haven't experienced something that would cause a non-zero exit, so hard to say exactly why you were getting one. Were you getting a specific code?

**Comment by rondale-sc** [comment]
I didn't actually capture the error code.  I think it was 127 or something. 

`cmd: <some error message>`  (just going off memory, it was strange)

Sorry I can't be more help.
