### ISSUE TITLE
Bin files are not consistently named

### ISSUE THREAD

**Issue by rondale-sc** [hashrocket/dotmatrix#26]
Found myself banging my head against the wall because my script couldn't find `bin/vimbundles`, but it correctly found `bin/install`.

This was because `bin/install` is without the sh extension and `bin/vimbunldes.sh` has it.  Not sure what this would entail (probably updating the docs and the files)  

Not sure if this is a big enough deal to change (as other scripts may rely on those names)

**Comment by jgdavey** [comment]
`vimbundles.sh` is deprecated. It moved to hashrocket/hr some time ago. I've been meaning to remove it from dotmatrix.

The other `*.sh` files are just helper scripts. Only `bin/install` and `bin/upgrade` are designed to be run from the command line, or to provision a server, etc.
