### ISSUE TITLE
Support for tmux 2.4+

### ISSUE THREAD

**Issue by bbuchalter** [hashrocket/dotmatrix#56]
After installing tmux 2.5, the following errors occur:
```
invalid or unknown command: bind -t vi-copy y copy-pipe 'reattach-to-user-namespace pbcopy'
invalid or unknown command: bind -t vi-copy v begin-selection
invalid or unknown command: bind -t vi-copy V rectangle-toggle
invalid or unknown command: bind-key -t vi-copy WheelUpPane halfpage-up
invalid or unknown command: bind-key -t vi-copy WheelDownPane halfpage-down
```

As a workaround, for those using macOS and homebrew, you can revert back to a previous version of tmux by first seeing what versions you had installed: `brew info tmux` and then switching: `brew switch tmux $VERSION`.

**Comment by bbuchalter** [comment]
There seems to be a fairly clear break in compatibility in the tmux config as discussed in https://github.com/tmux/tmux/issues/754. The question is now can we get a `.tmux.conf` that works for both versions, or does dotmatrix want to start declaring what versions of tmux it supports?

**Comment by dkarter** [comment]
@bbuchalter thanks for reporting this issue. I think it is best as a policy to support the newest version. If someone would like to stay on an old version they can checkout an older version of dotmatrix. If you would like to submit a PR based on the issue you mentioned I'd be happy to review it. Thanks!

**Comment by plicjo** [comment]
I've got it working with this syntax in `.tmux.conf`:

```
ind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X rectangle-toggle

# Mouse options for tmux >= 2.5
set-option -g -q mouse on
bind-key -T root WheelUpPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind-key -T root WheelDownPane if-shell -F -t = "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"
bind-key -T copy-mode-vi WheelUpPane send-keys -X halfpage-up
bind-key -T copy-mode-vi WheelDownPane send-keys -X halfpage-down
```

It works for me on with Tmux 2.5, but I had another developer using dotmatrix try it out and it didn't work for him.

**Comment by cbartlett** [comment]
@plicjo This also worked for me with tmux 2.5 on macOS 10.12.6. Thank you!
