### ISSUE TITLE
Possible to have a .vim folder with this?

### ISSUE THREAD

**Issue by BrandonShega** [hashrocket/dotmatrix#65]
Hi all,

I love the dotmatrix and how easy it is to set up.  I am curious though, right now I have everything in my own `.vimrc.local` but I've been thinking about splitting my files up into categories in the `.vim` folder, is this still possible using the dotmatrix?

Thanks!
Brandon

**Comment by dkarter** [comment]
@BrandonShega Thanks for trying out Dotmatrix!

What you are trying to do is indeed possible (if I understand you correctly).

You can split your settings into different files by sourcing those files from `.vimrc.local` the same way `.vimrc.local` is sourced from the main `.vimrc`.

For example:

```viml
" .vimrc.local
source ~/.vim/.general_settings
source ~/.vim/.keymapings
source ~/.vim/.plugins
```

**Comment by BrandonShega** [comment]
Ohh I see what you're saying, that makes sense.  Does it make sense at all for me to fork the dotmatrix and then just put my files in the `.vim` folder that gets symlinked and do it that way?

**Comment by dkarter** [comment]
Of course - you can do that too - but you will need to manually fetch upstream updates (if you care about that).

So in git you will need to add this repo as a remote and then fetch it every now and then and merge it into your own repo. I can give you a more specific list of commands for doing that if that would be helpful.

**Comment by dkarter** [comment]
And still you will need to source those in your vimrc/vimrc.local I'm not sure that vim will just load vimscripts in the .vim folder automatically.

**Comment by BrandonShega** [comment]
Great, thank you so much for all of the help, I'll probably just do what you suggested with sourcing the files.
