### ISSUE TITLE
.vimrc 'set visualbell', causing issue

### ISSUE THREAD

**Issue by MichaelDimmitt** [hashrocket/dotmatrix#68]
I find dotmatrix useful, 
<br>namely on my 2012-2015 macbook pro. (see computer specs)

However, for the year that I have been using dotmatrix my macbook gets stuck if I am using vim and scrolling to the end of a file. The amount of time being stuck is worse if I hugely overshoot the length of the file.

Having a fresh operating system I was able to replicate the issue and can easily replicate the issue again. 

## Problem
the problem lies in line 11 of .vimrc
<br>`set visualbell`

my understanding is that the visual bell is stopped 
<br>but awaits further instructions.

## Solution
I found the solution to the problem and can make a pull request if there is interest. 
<br>solution: add to line 12 of .vimrc
<br>`set t_vb=` #.note: this sets the effect of the vim visual bell to do nothing

I wanted to check two things with your team before opening a pull request,
1) If the current implementation had a particular use that I am unaware. (without set t_vb=)
2) New code will not cause trouble for users with different hardware and operating systems.

## Computer Specs,
macOS Seirra version: 10.12.6
<br>MacBook Pro (13-inch, Mid 2012)
<br>Processor: 2.9 GHz Intel Core i7

## Resource/Referance
solution sourced from: [disable audio/visual bells in vim](https://unix.stackexchange.com/questions/5310/how-can-i-disable-bells-visualbells-in-vim)

**Comment by mattpolito** [comment]
Closing as per #69
