### ISSUE TITLE
Battery command has no output

### ISSUE THREAD

**Issue by avogel3** [hashrocket/dotmatrix#87]
Running the following command has no output:
```
hr battery
```

**System:** 2017 Macbook Pro 15"
**OS:** OSX Mojave 10.14.6

**Comment by jgdavey** [comment]
What about `hr battery --charging`? Does that also have no output? By default, the command only outputs if using battery power (not plugged in), while with this flag prints the percentage regardless.

**Comment by avogel3** [comment]
@jgdavey Thanks for the info, works exactly as you described 👍
