### ISSUE TITLE
hr: no such command `autoinstall'

### ISSUE THREAD

**Issue by BrandonShega** [hashrocket/dotmatrix#88]
I'm using a fork of dotmatrix to manage my own dot files and I don't seem to have the `hr` command in my path.  If I go to my fork and run `bin/install` I get `hr: no such command autoinstall`.  I've pulled the latest from the upstream and merged it into my fork but I still can't seem to get this to work, is it something I have misconfigured?

**Comment by jwworth** [comment]
Thanks for raising this issue, @BrandonShega! I think I've seen that error before, but can't seem to reproduce it now. Are your dotfiles open source by chance? That would be helpful for trying to reproduce the issue.

Tagging @jgdavey

**Comment by BrandonShega** [comment]
@jwworth They are, they're located here https://github.com/BrandonShega/dotmatrix

**Comment by jgdavey** [comment]
I was able to reproduce this in a totally "clean" bash shell (`env -i bash --norc --noprofile`).

The fix oddly enough is to change the `hr/bin/hr` command to just be a symlink to the `hr/libexec/hr` script. I'll do a PR shortly.

**Comment by jgdavey** [comment]
Actually, it looks like that's *already* how dotmatrix is set up. Here are some commands that should work for you to get it back in order:

```
# In your dotmatrix dir:
$ rm hr/bin/hr
$ ln -nfs ../libexec/hr hr/bin/hr
$ git commit -a -m "Fix hr binary"
```

**Comment by BrandonShega** [comment]
@jgdavey Thanks, that looks like it did the trick for me.  Sorry for the late response, I took quite the long break over the holidays and didn't get a chance to get this back and working.
